### ISSUE TITLE
the generating script fails on most recent transactsqldom nuget

### ISSUE THREAD

**Issue by smoothdeveloper** [isaksky/FsSqlDom#4]
Just to track the issue, tried running it on the v15 of the nuget and seems to mishandle two things:

* need to escape `type` keyword the same way it is done in other
* need to change the logic outputing the type name in the DU fields as it can refer to inner types

**Comment by isaksky** [comment]
Thanks, I'll check that out.

**Comment by isaksky** [comment]
Should work now, let me know if you see any issues. I haven't been able to test it yet, since it looks like the paket/fake build stuff is broken.
